# Project
version=2.0.0-1.21.1
group=net.johnpgr.craftingtableiifabric
java_version=21

# Mod metadata
mod.id=craftingtableiifabric
mod.name=CraftingTableII Refabricated
mod.version=2.0.0-1.21.1
mod.group=net.johnpgr.craftingtableiifabric

# Publish metadata
minecraft_version=1.21.1
mod_name=CraftingTableII Refabricated
mod_author=johnpgr
mod_id=craftingtableiifabric
license=MIT
credits=
description=CraftingTableII Refabricated is a port of perky's Crafting Table II to Modern Minecraft.
minecraft_version_range=[1.21.1, 1.21.2)
neo_form_version=1.21.1-20240808.144430
parchment_minecraft=1.21
parchment_version=2024.11.10
fabric_version=0.107.0+1.21.1
fabric_loader_version=0.16.9
neoforge_version=21.1.80
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Gradle Plugins
mod_publish_version=2.0.0
github_api_version=1.314
grgit_version=5.2.2

# Publish
modrinth_id=gnSVsvlY
curseforge_id=974793

# Minecraft line
mod.mc_title=1.21.1
mod.mc_targets_fabric=["1.21.1"]
mod.mc_targets_range=[1.21.1, 1.21.2)
mod.java_version=21

# Dependencies
dep.minecraft.fabric=1.21.1
dep.minecraft.neoforge=1.21.1
dep.fabric_loader=0.16.9
dep.fabric_api_version=0.107.0+1.21.1
dep.neoforge_loader=21.1.80
dep.neoforge_loader_range=[4,)
dep.neoforge_version_range=[21.1,)
dep.parchment_minecraft=1.21
dep.parchment_version=2024.11.10
dep.loom_version=1.10-SNAPSHOT
