# gradle/targets/1.21.3.properties
mod.mc_title=1.21.3
mod.mc_targets_fabric=["1.21.2", "1.21.3"]
mod.mc_targets_range=[1.21.2, 1.21.4)
mod.java_version=21

dep.minecraft.fabric=1.21.3
dep.minecraft.neoforge=1.21.3
dep.fabric_loader=0.16.9
dep.fabric_api_version=0.107.0+1.21.3
dep.neoforge_loader=21.3.96
dep.neoforge_loader_range=[4,)
dep.neoforge_version_range=[21.3,)
dep.parchment_minecraft=1.21.3
dep.parchment_version=2024.12.07
dep.loom_version=1.10-SNAPSHOT
