# gradle/targets/1.21.6.properties
mod.mc_title=1.21.6
mod.mc_targets_fabric=["1.21.6", "1.21.7", "1.21.8"]
mod.mc_targets_range=[1.21.6, 1.21.9)
mod.java_version=21

dep.minecraft.fabric=1.21.6
dep.minecraft.neoforge=1.21.6
dep.fabric_loader=0.17.2
dep.fabric_api_version=0.128.2+1.21.6
dep.neoforge_loader=21.6.20-beta
dep.neoforge_loader_range=[4,)
dep.neoforge_version_range=[21.6,)
dep.parchment_minecraft=1.21.6
dep.parchment_version=2025.06.29
dep.loom_version=1.10-SNAPSHOT
