# gradle/targets/1.21.5.properties
mod.mc_title=1.21.5
mod.mc_targets_fabric=["1.21.5"]
mod.mc_targets_range=[1.21.5, 1.21.6)
mod.java_version=21

dep.minecraft.fabric=1.21.5
dep.minecraft.neoforge=1.21.5
dep.fabric_loader=0.17.2
dep.fabric_api_version=0.128.2+1.21.5
dep.neoforge_loader=21.5.97
dep.neoforge_loader_range=[4,)
dep.neoforge_version_range=[21.5,)
dep.parchment_minecraft=1.21.5
dep.parchment_version=2025.06.15
dep.loom_version=1.10-SNAPSHOT
